version: '3.8'

services:
  julaw:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: julaw
    container_name: julaw-ui
    volumes:
      - ./config/nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - julaw-ui

networks:
  julaw-ui: 
   